#!/bin/bash
#
# auto-commit.sh - Automatically commit and push changes
#
# Usage:
#   ./auto-commit.sh <project-path> <commit-type> <commit-message>
#
# Commit types:
#   feat, fix, refactor, docs, test, chore, ai
#
# Examples:
#   ./auto-commit.sh /opt/openclaw/workspace/my-bot feat "Add user authentication"
#   ./auto-commit.sh /opt/openclaw/workspace/my-bot ai "Generate UserService class"

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

if [[ $# -lt 3 ]]; then
    echo "Usage: $0 <project-path> <commit-type> <commit-message>"
    echo ""
    echo "Commit types: feat, fix, refactor, docs, test, chore, ai"
    exit 1
fi

PROJECT_PATH="$1"
COMMIT_TYPE="$2"
COMMIT_MESSAGE="$3"

# Validate commit type
VALID_TYPES=("feat" "fix" "refactor" "docs" "test" "chore" "ai")
if [[ ! " ${VALID_TYPES[*]} " =~ " ${COMMIT_TYPE} " ]]; then
    echo -e "${RED}Invalid commit type: $COMMIT_TYPE${NC}"
    echo "Valid types: ${VALID_TYPES[*]}"
    exit 1
fi

if [[ ! -d "$PROJECT_PATH" ]]; then
    echo -e "${RED}Error: Project path does not exist: $PROJECT_PATH${NC}"
    exit 1
fi

cd "$PROJECT_PATH"

# Check if git repository
if [[ ! -d .git ]]; then
    echo -e "${RED}Error: Not a Git repository${NC}"
    exit 1
fi

echo "Auto-commit: $COMMIT_MESSAGE"
echo "Path: $PROJECT_PATH"
echo ""

# Check for changes
CHANGES=$(git status --porcelain | wc -l)
if [[ $CHANGES -eq 0 ]]; then
    echo "No changes to commit"
    exit 0
fi

echo "Changes detected: $CHANGES files"
echo ""

# Stage all changes
echo "Staging changes..."
git add -A

# Build commit message
COMMIT_FULL="${COMMIT_TYPE}: ${COMMIT_MESSAGE}

Generated by: OpenClaw Gateway
Date: $(date -Iseconds)"

# Commit
echo "Creating commit..."
if git commit -m "$COMMIT_FULL"; then
    echo -e "${GREEN}✅ Committed${NC}"

    # Show commit hash
    HASH=$(git rev-parse --short HEAD)
    echo "  Hash: $HASH"
else
    echo -e "${RED}Failed to commit${NC}"
    exit 1
fi

# Auto-push if enabled
if [[ "${AUTO_PUSH:-true}" == "true" ]]; then
    # Check if remote exists
    if git remote get-url origin &>/dev/null; then
        echo ""
        echo "Pushing to remote..."
        BRANCH=$(git rev-parse --abbrev-ref HEAD)

        if git push origin "$BRANCH"; then
            echo -e "${GREEN}✅ Pushed${NC}"
        else
            echo -e "${YELLOW}Failed to push (will retry later)${NC}"
            exit 1
        fi
    else
        echo "No remote configured, skipping push"
    fi
fi

echo ""
echo -e "${GREEN}✅ Auto-commit complete${NC}"
